"""empty message

Revision ID: 73fb3c9bdd54
Revises: c6f9aefa97c7
Create Date: 2024-09-02 14:11:47.076142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fb3c9bdd54'
down_revision = 'c6f9aefa97c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ActiveRoute', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('TotalRanKMS', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('TotalRanKMS')
        batch_op.drop_column('ActiveRoute')

    # ### end Alembic commands ###
