"""empty message

Revision ID: 81b460d49f60
Revises: 
Create Date: 2024-09-03 13:23:01.114302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b460d49f60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Token', sa.String(length=50), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=400), nullable=False),
    sa.Column('ActiveRoute', sa.String(length=100), nullable=True),
    sa.Column('ActiveRouteMeters', sa.Integer(), nullable=True),
    sa.Column('TotalRanMeters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
